apiVersion: apps/v1
kind: Deployment
metadata:
  name: flickr-api-deployment
spec:
  selector:
    matchLabels:
      app: flickr-api
  replicas: 2
  template:
    metadata:
      labels:
        app: flickr-api
    spec:
      containers:
      - name: flickr-api
        image: jonbern/flickr-api:latest
        ports:
          - containerPort: 8088
        env:
          - name: PORT
            value: "8088"
          - name: API_KEY
            value: {{ .Values.flickrApi.apiKey }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flickr-frontend-deployment
spec:
  selector:
    matchLabels:
      app: flickr-frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: flickr-frontend
    spec:
      containers:
      - name: flickr-frontend
        image: jonbern/flickr-frontend
        ports:
          - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
          - name: API_BASE_URL
            value: http://{{ .Values.api.host }}:30061/api
